import { Inter } from 'next/font/google';
import './globals.css';
import { useEffect } from 'react';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  useEffect(() => {
    if ('serviceWorker' in navigator) {
      navigator.serviceWorker.register('/sw.js').then(function(registration) {
        console.log('Service Worker registered with scope:', registration.scope);
      }).catch(function(error) {
        console.log('Service Worker registration failed:', error);
      });
    }
  }, []);

  return (
    <html lang='en'>
      <head>
        <link rel='manifest' href='/manifest.json'/>
        <meta name='theme-color' content='#000000' />
        <link rel='apple-touch-icon' href='/icons/icon-192x192.png' />
      </head>
      <body className={inter.className}>{children}</body>
    </html>
  );
}